name: deploy-cloudflare-worker

on:
  push:
  workflow_dispatch:

concurrency:
  group: deploy-cloudflare-worker-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.0
      - uses: ./.github/actions/setup-bun
      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24.15.0

      - name: Cache bestdori responses
        uses: actions/cache@v6.1.0
        with:
          path: site/.bestdori-cache
          key: bestdori-response-${{ github.run_id }}
          restore-keys: bestdori-response-

      - name: Build site
        run: npm run build
        working-directory: site/
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          UMAMI_SITE_ID: ${{ vars.UMAMI_SITE_ID }}

      - name: Fix bundled assets (CSS) got lost somehow someway
        run: cp dist/server/_astro/* dist/client/_astro
        working-directory: site/

      - name: Upload site build artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: site
          include-hidden-files: true
          path: |
            site/dist/
            site/.wrangler/

      - name: Deploy to Cloudflare Workers
        id: deploy-cloudflare-worker
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: cloudflare/wrangler-action@v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
          workingDirectory: site/
          secrets: |
            DATABASE_URL
            DATABASE_AUTH_TOKEN
            DISCORD_APPLICATION_ID
            DISCORD_APPLICATION_PUBLIC_KEY
            UPSTASH_REDIS_REST_URL
            UPSTASH_REDIS_REST_TOKEN
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_AUTH_TOKEN: ${{ secrets.DATABASE_AUTH_TOKEN }}
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_APPLICATION_PUBLIC_KEY: ${{ secrets.DISCORD_APPLICATION_PUBLIC_KEY }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}

      - name: Register Discord commands
        if: ${{ github.ref == 'refs/heads/main' }}
        run: bun run src/register.ts
        working-directory: packages/discord-bot
        env:
          DISCORD_APPLICATION_ID: ${{ secrets.DISCORD_APPLICATION_ID }}
          DISCORD_APPLICATION_TOKEN: ${{ secrets.DISCORD_APPLICATION_TOKEN }}
